import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="h-full" lang="en">
      <body className={cn("h-full relative font-sans antialiased", inter.className)}>
        <main className='min-h-screen relative flex flex-col'>
          <NavBar />
          <div className="flex-grow flex-1">{children}</div>
        </main>
      </body>
    </html>
  )
}
